// Seed / fallback content. Kept free of any Firebase import so it can be
// bundled into the initial app load without pulling in the Firebase SDK.

export const SEED_PRODUCTS = [
    {
        id: 1, slug: 'fingers-a', order: 1, featured: true,
        image: '/images-new/product-1.jpg',
        title_ru: 'Бочонок A', title_en: 'Fingers A',
        desc_ru: 'Корень солодки, нарезанный на отрезки длиной 5-8 см, отборная резка по размеру (диаметр A — большой).',
        desc_en: 'Licorice root cut into 5-8 cm lengths, selected cut by size (diameter A — large).',
        specs: {
            botanical_name: 'Glycyrrhiza glabra',
            origin: 'Uzbekistan',
            part_used: 'Root',
            cultivation: 'Wild + artificial',
            form_cut_type: 'Fingers (cut root)',
            cut_size: '5–8 cm',
            diameter_grade: 'A (large)',
            processing: 'Standard',
            packaging: 'PP bags 25 kg',
            moq: '',
            moisture: '≤ 8%',
            ash: '≤ 9%',
            glycyrrhizin: '≥ 4%',
            foreign_matter: '≤ 1%',
            heavy_metals: 'Within WHO/EU limits',
            pesticide_residues: 'Within WHO/EU limits',
            tpc: '≤ 100,000 CFU/g',
            yeast_mould: '≤ 1,000 CFU/g',
            e_coli: 'Absent',
            salmonella: 'Absent',
            shelf_life: '24 months',
            storage: '≤ 25°C, cool and dry, away from sunlight',
        },
    },
    {
        id: 2, slug: 'fingers-peeled-mix', order: 2, featured: false,
        image: '/images-new/product-2.jpg',
        title_ru: 'Бочонок очищенный mix', title_en: 'Fingers Peeled mix',
        desc_ru: 'Очищенный корень солодки, нарезанный на отрезки длиной 5-8 см, смешанная фракция.',
        desc_en: 'Peeled licorice root cut into 5-8 cm lengths, mixed sizes.',
    },
    {
        id: 3, slug: 'granules', order: 3, featured: true,
        image: '/images-new/product-3.jpg',
        title_ru: 'Гранулы', title_en: 'Granules',
        desc_ru: 'Корень солодки в гранулированной нарезке.',
        desc_en: 'Licorice root cut into granules.',
    },
    {
        id: 4, slug: 'crushed', order: 4, featured: false,
        image: '/images-new/product-4.jpg',
        title_ru: 'Измельчённый', title_en: 'Crushed',
        desc_ru: 'Корень солодки измельчённый, смешанный помол.',
        desc_en: 'Crushed licorice root, mixed grind.',
    },
    {
        id: 5, slug: 'standard-sticks', order: 5, featured: false,
        image: '/images-new/product-5.jpg',
        title_ru: 'Палочки отборные стд', title_en: 'Standard Caliber Sticks',
        desc_ru: 'Корень солодки нарезки стандартного калибра.',
        desc_en: 'Licorice root cut into sticks of standard calibre.',
    },
    {
        id: 6, slug: 'selected-sticks', order: 6, featured: false,
        image: '/images-new/product-6.jpg',
        title_ru: 'Палочки отборные', title_en: 'Selected Sticks',
        desc_ru: 'Корень солодки нарезанный палочками, отборные по размеру.',
        desc_en: 'Licorice root cut into sticks selected by size.',
    },
    {
        id: 7, slug: 'peeled-sticks', order: 7, featured: false,
        image: '/images-new/product-7.jpg',
        title_ru: 'Палочки очищенные', title_en: 'Peeled Sticks',
        desc_ru: 'Очищенный корень солодки в палочках.',
        desc_en: 'Peeled licorice root cut into sticks.',
    },
    {
        id: 8, slug: 'powder', order: 8, featured: true,
        image: '/images-new/product-8.jpg',
        title_ru: 'Порошок', title_en: 'Powder',
        desc_ru: 'Корень солодки полу-мелкого помола, порошкообразный.',
        desc_en: 'Licorice root semi-fine grind, powdered.',
    },
    {
        id: 9, slug: 'slice-a', order: 9, featured: false,
        image: '/images-new/product-9.jpg',
        title_ru: 'Слайс A', title_en: 'Slice A',
        desc_ru: 'Корень солодки резаный, отборные срезы по размеру (диаметр A — большой).',
        desc_en: 'Sliced licorice root, selected slices by size (diameter A — large).',
    },
    {
        id: 10, slug: 'slice-mix', order: 10, featured: false,
        image: '/images-new/product-10.jpg',
        title_ru: 'Слайс mix', title_en: 'Slice Mix',
        desc_ru: 'Корень солодки резаный, смешанная фракция.',
        desc_en: 'Sliced licorice root, mixed fraction.',
    },
    {
        id: 11, slug: 'tablet-a', order: 11, featured: false,
        image: '/images-new/product-11.jpg',
        title_ru: 'Таблетка A', title_en: 'Tablet A',
        desc_ru: 'Корень солодки нарезанный таблеткой, отборное по размеру (диаметр A — большой).',
        desc_en: 'Licorice root cut into tablets, selected by size (diameter A — large).',
    },
    {
        id: 13, slug: 'tablet-mix', order: 12, featured: false,
        image: '/images-new/product-13.jpg',
        title_ru: 'Таблетка mix', title_en: 'Tablet Mix',
        desc_ru: 'Корень солодки нарезанный вертикально, смешанные размеры.',
        desc_en: 'Licorice root cut vertically, mixed sizes.',
    },
    {
        id: 14, slug: 'chips', order: 13, featured: false,
        image: '/images-new/product-14.jpg',
        title_ru: 'Щепки', title_en: 'Chips',
        desc_ru: 'Корень солодки дроблённый в виде щепки.',
        desc_en: 'Crushed licorice root in chip form.',
    },
    {
        id: 15, slug: 'custom-order', order: 14, featured: false,
        image: '/images-new/product-15.jpg',
        title_ru: 'Индивидуальный заказ', title_en: 'Custom Order',
        desc_ru: 'Производство и поставка корня солодки по индивидуальным требованиям.',
        desc_en: 'Production and supply of licorice root according to individual requirements.',
    },
    {
        id: 16, slug: 'extract', order: 15, featured: true,
        image: '/images-new/product-16.png',
        title_ru: 'Экстракт корня солодки', title_en: 'Licorice Root Extract',
        desc_ru: 'Экстракт корня солодки в порошкообразной и жидкой форме.',
        desc_en: 'Licorice root extract in powdered and liquid form.',
    },
];

export const SEED_TRANSLATIONS = {
    languages: [
        { code: 'ru', label: 'RU', name: 'Русский' },
        { code: 'en', label: 'EN', name: 'English' },
    ],
    ru: {
        home: 'Главная',
        products: 'Каталог',
        about: 'О Компании',
        contact: 'Контакты',
        contactBtn: 'Связаться',
        read_more: 'Подробнее',
        // SEO
        meta_title: 'Bogot Master | Экспорт корня солодки из Узбекистана',
        meta_description: 'Bogot Master — ведущий производитель и экспортер корня солодки в Узбекистане. Оптовые поставки экстракта, корня, слайсов и гранул солодки по всему миру.',
        meta_keywords: 'корень солодки, солодка оптом, экспорт солодки, экстракт солодки, Узбекистан, Bogot Master, licorice root, licorice',
        og_title: 'Bogot Master | Экспорт Качественной Солодки',
        og_description: 'Производство и экспорт корня солодки высшего качества из Узбекистана. Надежный партнер для вашего бизнеса.',
        schema_description: 'Семейная компания, специализирующаяся на заготовке, переработке и экспорте корня солодки из Узбекистана.',
        hero_image_alt: 'Корни солодки из Узбекистана',
        // Per-page SEO
        notfound_title: 'Страница не найдена | Bogot Master',
        notfound_heading: 'Страница не найдена',
        notfound_text: 'К сожалению, запрашиваемая страница не существует или была перемещена.',
        notfound_home: 'Вернуться на главную',
        products_meta_title: 'Продукция — Корень солодки оптом | Bogot Master',
        products_meta_desc: 'Полный каталог продукции из корня солодки: палочки, слайсы, гранулы, порошок и экстракт. Оптовые поставки из Узбекистана по всему миру.',
        about_meta_title: 'О компании | Экспортёр солодки | Bogot Master',
        about_meta_desc: 'Bogot Master — семейная компания с 2014 года, заготовка, переработка и экспорт корня солодки из Узбекистана. До 1500 тонн в год.',
        contact_meta_title: 'Контакты | Запросить предложение | Bogot Master',
        contact_meta_desc: 'Свяжитесь с Bogot Master для оптовых поставок корня солодки. Получите индивидуальное коммерческое предложение для вашего бизнеса.',
        // Quote cart
        quote_add: 'В запрос',
        quote_added: 'Добавлено',
        quote_cart_title: 'Запрос предложения',
        quote_empty: 'Список пуст. Добавьте товары для запроса предложения.',
        quote_qty_placeholder: 'Кол-во (напр. 1 тонна)',
        quote_remove: 'Удалить',
        quote_clear: 'Очистить список',
        quote_company: 'Компания',
        quote_submit: 'Отправить запрос',
        quote_success: 'Спасибо! Запрос отправлен. Мы свяжемся с вами в ближайшее время.',
        // About
        about_title: 'О компании',
        about_p1: 'Bogot Master — семейная компания, основанная в 2014 году, специализирующаяся на заготовке, переработке и экспорте корня солодки.',
        about_p2: 'Компания осуществляет экспорт корня солодки в различных формах поставки и работает со всеми необходимыми разрешительными документами и сертификатами, в соответствии с требованиями стран-импортёров.',
        about_p3: 'Производственные и заготовительные мощности Bogot Master позволяют осуществлять экспорт до 1 500 тонн корня солодки в год. В деятельности компании задействовано более 20 сотрудников, обеспечивающих контроль качества, переработку, упаковку и логистику продукции.',
        about_p4: 'Заготовка корня солодки осуществляется с соблюдением установленных технологических и экологических требований. Компания ориентирована на стабильные долгосрочные поставки и индивидуальный подход к требованиям заказчиков по форме, фракции и упаковке продукции.',
        about_benefit_1: 'Поставка по всему Миру',
        about_benefit_2: 'Сотрудничество на оптом',
        about_benefit_3: 'Качество и сертификация',
        about_benefit_4: 'Все виды в наличии круглый год',
        about_img_1: 'Склад хранения солодки',
        about_img_2: 'Работник с продукцией',
        about_img_3: 'Погрузка в грузовик',
        consultation_title: 'Консультация о компании',
        // Products
        our_products: 'Наша Продукция',
        view_all_products: 'Смотреть все продукты',
        related_products: 'Похожие продукты',
        get_price: 'Узнать цену',
        specifications: 'Технические характеристики',
        // Hero
        hero_cta: 'Запросить коммерческое предложение',
        hero_modal_title: 'Коммерческое предложение',
        // Certificates
        certificates_title: 'Наши Сертификаты',
        documentation_label: 'Документация',
        cert_1: 'Выписка из реестра',
        cert_2: 'Свидетельство НДС',
        cert_3: 'Свидетельство о регистрации',
        cert_4: 'Удостоверение о регистрации',
        // Gallery & Partners
        gallery_title: 'Галерея',
        gallery_item_alt: 'Изображение галереи',
        partners_label: 'Доверие',
        partners_title: 'Наши Партнеры',
        partner_alt: 'Логотип партнера',
        // Contact
        contact_title: 'Контакты',
        contact_cta_title: 'Вам нужна дополнительная информация?',
        contact_cta_text: 'Напишите нам и наш специалист перезвонит вам.',
        contact_cta_btn: 'Написать',
        contact_address: 'Адрес',
        address_line_1: '220204, Боготский район,',
        address_line_2: 'Хорезмская область, Республика Узбекистан.',
        contact_phone: 'Номер телефона',
        contact_email: 'Почта',
        contact_website: 'Сайт',
        form_name: 'Ф.И.О',
        form_name_placeholder: 'Иван Иванов',
        form_email: 'Ваша почта',
        form_email_placeholder: 'ivan@example.com',
        form_email_error: 'Введите email',
        form_email_invalid: 'Неверный формат email',
        form_comment: 'Комментарий',
        form_success: '✓ Сообщение отправлено! Мы свяжемся с вами в ближайшее время.',
        form_error: '✗ Произошла ошибка. Попробуйте позже или свяжитесь с нами напрямую.',
        form_submit: 'Отправить',
        form_sending: 'Отправка...',
        // Social
        social_msg_product: 'Здравствуйте! Интересует {product}. Можете предоставить информацию о цене?',
        social_msg_general: 'Здравствуйте! Хочу узнать больше о вашей продукции.',
        // Footer
        footer_slogan: 'Совершенство в каждой детали.',
        footer_quick_links: 'Быстрые ссылки',
        footer_contact_us: 'Связаться с нами',
        footer_rights: 'Все права защищены.',
        // Home Stats
        stat_years: 'Лет на рынке',
        stat_tons: 'Тонн ежегодно',
        stat_experts: 'Специалистов',
        stat_clients: 'B2B Клиентов',
        // Process
        process_label: 'Технология',
        process_title: 'Наш процесс',
        process_subtitle: 'Прозрачная цепочка поставок: от дикорастущего корня до готового продукта высшего сорта.',
        process_stage: 'Этап',
        process_1_title: 'Эко-заготовка',
        process_1_desc: 'Сезонный сбор зрелых корней в экологически чистых поймах рек Узбекистана с соблюдением норм устойчивого природопользования.',
        process_2_title: 'Стандартизация',
        process_2_desc: 'Автоматизированная мойка, калибровка и деликатная сушка в специализированных камерах для сохранения глицирризиновой кислоты.',
        process_3_title: 'Лабораторный контроль',
        process_3_desc: 'Физико-химический анализ каждой партии в собственной лаборатории на соответствие международным стандартам чистоты и безопасности.',
        process_4_title: 'Глобальная логистика',
        process_4_desc: 'Вакуумная упаковка и консолидация грузов для бесперебойных B2B поставок в любую точку мира с полным пакетом документов.',
        // About Extra
        about_extra_stat_tons: 'Тонн продукции в год',
        about_extra_stat_staff: 'Квалифицированных сотрудников',
        // Product Specs
        spec_identity: 'Идентификация',
        spec_physical: 'Физические показатели',
        spec_quality: 'Качество',
        spec_microbiology: 'Микробиология',
        spec_storage_shelf: 'Хранение и срок годности',
        spec_botanical_name: 'Ботаническое название',
        spec_origin: 'Происхождение',
        spec_part_used: 'Используемая часть',
        spec_cultivation: 'Культивация',
        spec_form_cut_type: 'Форма / тип нарезки',
        spec_cut_size: 'Размер / длина нарезки',
        spec_diameter_grade: 'Грейд диаметра',
        spec_processing: 'Обработка',
        spec_packaging: 'Упаковка',
        spec_moq: 'Минимальный заказ',
        spec_moisture: 'Влажность',
        spec_ash: 'Зольность',
        spec_glycyrrhizin: 'Глицирризин',
        spec_foreign_matter: 'Примеси',
        spec_heavy_metals: 'Тяжелые металлы',
        spec_pesticide_residues: 'Остатки пестицидов',
        spec_tpc: 'Общее микробное число (TPC)',
        spec_yeast_mould: 'Дрожжи и плесень',
        spec_e_coli: 'Кишечная палочка (E. coli)',
        spec_salmonella: 'Сальмонелла',
        spec_shelf_life: 'Срок годности',
        spec_storage: 'Условия хранения',
        spec_accompanying_docs: 'Сопроводительные документы',
        // Modals
        modal_price_title: 'Запрос цены',
        modal_info_title: 'Запрос дополнительной информации',
        modal_phone: 'Телефон',
        modal_phone_error: 'Введите номер телефона',
        modal_phone_invalid: 'Неверный формат телефона',
        modal_quantity: 'Количество',
        modal_quantity_error: 'Укажите количество',
        modal_quantity_placeholder: 'Например: 100 кг, 1 тонна',
        modal_comment_placeholder: 'Дополнительная информация...',
        modal_submit: 'Отправить запрос',
        modal_success_title: 'Запрос отправлен!',
        modal_success: 'Спасибо! Мы свяжемся с вами в ближайшее время.',
        modal_error: 'Произошла ошибка. Попробуйте позже.',
    },
    en: {
        home: 'Home',
        products: 'Products',
        about: 'About',
        contact: 'Contact',
        contactBtn: 'Contact Us',
        read_more: 'Read More',
        // SEO
        meta_title: 'Bogot Master | Licorice Root Export from Uzbekistan',
        meta_description: 'Bogot Master is a leading manufacturer and exporter of licorice root in Uzbekistan. Wholesale supply of licorice extract, root, slices, and granules worldwide.',
        meta_keywords: 'licorice root, licorice wholesale, licorice export, licorice extract, Uzbekistan, Bogot Master',
        og_title: 'Bogot Master | Premium Licorice Export',
        og_description: 'Production and export of high-quality licorice root from Uzbekistan. A reliable partner for your business.',
        schema_description: 'Family-owned company specializing in the harvesting, processing, and export of licorice root from Uzbekistan.',
        hero_image_alt: 'Licorice Roots from Uzbekistan',
        // Per-page SEO
        notfound_title: 'Page Not Found | Bogot Master',
        notfound_heading: 'Page Not Found',
        notfound_text: 'Sorry, the page you are looking for does not exist or has been moved.',
        notfound_home: 'Back to Home',
        products_meta_title: 'Products — Wholesale Licorice Root | Bogot Master',
        products_meta_desc: 'Full catalog of licorice root products: sticks, slices, granules, powder and extract. Wholesale supply from Uzbekistan worldwide.',
        about_meta_title: 'About | Licorice Exporter | Bogot Master',
        about_meta_desc: 'Bogot Master is a family-owned company since 2014: harvesting, processing and export of licorice root from Uzbekistan. Up to 1,500 tons annually.',
        contact_meta_title: 'Contact | Request a Quote | Bogot Master',
        contact_meta_desc: 'Contact Bogot Master for wholesale licorice root supply. Get a personalized commercial proposal for your business.',
        // Quote cart
        quote_add: 'Add to quote',
        quote_added: 'Added',
        quote_cart_title: 'Request a Quote',
        quote_empty: 'Your list is empty. Add products to request a quote.',
        quote_qty_placeholder: 'Qty (e.g. 1 ton)',
        quote_remove: 'Remove',
        quote_clear: 'Clear list',
        quote_company: 'Company',
        quote_submit: 'Send Request',
        quote_success: 'Thank you! Your request has been sent. We will contact you shortly.',
        // About
        about_title: 'About Company',
        about_p1: 'Bogot Master is a family-owned company established in 2014, specializing in the harvesting, processing, and export of licorice root.',
        about_p2: 'The company supplies licorice root in multiple forms and operates in full compliance with international trade regulations, holding all required permits and certificates in accordance with the standards of importing countries.',
        about_p3: 'Bogot Master\'s harvesting and processing capacity enables the export of up to 1,500 tons of licorice root annually. The company employs over 20 specialists who ensure consistent quality control, processing, packaging, and efficient logistics.',
        about_p4: 'Licorice root is harvested in strict accordance with approved technological and environmental standards. Bogot Master is committed to long-term, reliable partnerships and offers a flexible, customer-oriented approach to product form, size fraction, and packaging requirements.',
        about_benefit_1: 'Worldwide supply',
        about_benefit_2: 'Wholesale cooperation',
        about_benefit_3: 'Certified quality standards',
        about_benefit_4: 'Year-round product availability',
        about_img_1: 'Warehouse storage',
        about_img_2: 'Worker with product',
        about_img_3: 'Truck loading',
        consultation_title: 'Consultation about company',
        // Products
        our_products: 'Our Products',
        view_all_products: 'View All Products',
        related_products: 'Related Products',
        get_price: 'Get Price',
        specifications: 'Technical Specifications',
        // Hero
        hero_cta: 'Request Commercial Proposal',
        hero_modal_title: 'Commercial Proposal',
        // Certificates
        certificates_title: 'Our Certificates',
        documentation_label: 'Documentation',
        cert_1: 'Registry Extract',
        cert_2: 'VAT Certificate',
        cert_3: 'Registration Certificate',
        cert_4: 'Registration ID',
        // Gallery & Partners
        gallery_title: 'Gallery',
        gallery_item_alt: 'Gallery image',
        partners_label: 'Trust',
        partners_title: 'Our Partners',
        partner_alt: 'Partner logo',
        // Contact
        contact_title: 'Contacts',
        contact_cta_title: 'Need more information?',
        contact_cta_text: 'Write to us and our specialist will call you back.',
        contact_cta_btn: 'Write to us',
        contact_address: 'Address',
        address_line_1: '220204, Bogot district,',
        address_line_2: 'Khorezm region, Republic of Uzbekistan.',
        contact_phone: 'Phone Number',
        contact_email: 'Email',
        contact_website: 'Website',
        form_name: 'Full Name',
        form_name_placeholder: 'John Doe',
        form_email: 'Your Email',
        form_email_placeholder: 'john@example.com',
        form_email_error: 'Enter email',
        form_email_invalid: 'Invalid email format',
        form_comment: 'Comment',
        form_success: '✓ Message sent! We will contact you shortly.',
        form_error: '✗ An error occurred. Please try again later or contact us directly.',
        form_submit: 'Submit',
        form_sending: 'Sending...',
        // Social
        social_msg_product: 'Hello! I am interested in {product}. Could you please provide price information?',
        social_msg_general: 'Hello! I would like to learn more about your products.',
        // Footer
        footer_slogan: 'Excellence in every detail.',
        footer_quick_links: 'Quick Links',
        footer_contact_us: 'Contact Us',
        footer_rights: 'All rights reserved.',
        // Home Stats
        stat_years: 'Years on market',
        stat_tons: 'Tons annually',
        stat_experts: 'Experts',
        stat_clients: 'B2B Clients',
        // Process
        process_label: 'Technology',
        process_title: 'Our Process',
        process_subtitle: 'Transparent supply chain: from wild-harvested root to premium-grade finished product.',
        process_stage: 'Stage',
        process_1_title: 'Sustainable Harvest',
        process_1_desc: 'Seasonal collection of mature roots in ecologically clean floodplains of Uzbekistan, adhering to sustainable forestry standards.',
        process_2_title: 'Standardization',
        process_2_desc: 'Automated washing, grading, and controlled drying in specialized chambers to preserve glycyrrhizic acid content.',
        process_3_title: 'Quality Assurance',
        process_3_desc: 'Physicochemical analysis of every batch in our dedicated laboratory to ensure compliance with global purity and safety standards.',
        process_4_title: 'Global Logistics',
        process_4_desc: 'Secure packaging and cargo consolidation for seamless B2B supplies worldwide, accompanied by comprehensive documentation.',
        // About Extra
        about_extra_stat_tons: 'Tons of products annually',
        about_extra_stat_staff: 'Qualified employees',
        // Product Specs
        spec_identity: 'Identity',
        spec_physical: 'Physical',
        spec_quality: 'Quality',
        spec_microbiology: 'Microbiology',
        spec_storage_shelf: 'Storage & Shelf Life',
        spec_botanical_name: 'Botanical name',
        spec_origin: 'Origin',
        spec_part_used: 'Part used',
        spec_cultivation: 'Cultivation',
        spec_form_cut_type: 'Form / cut type',
        spec_cut_size: 'Cut size / length',
        spec_diameter_grade: 'Diameter grade',
        spec_processing: 'Processing',
        spec_packaging: 'Packaging',
        spec_moq: 'MOQ',
        spec_moisture: 'Moisture',
        spec_ash: 'Ash',
        spec_glycyrrhizin: 'Glycyrrhizin',
        spec_foreign_matter: 'Foreign matter',
        spec_heavy_metals: 'Heavy metals',
        spec_pesticide_residues: 'Pesticide residues',
        spec_tpc: 'TPC',
        spec_yeast_mould: 'Yeast & Mould',
        spec_e_coli: 'E. coli',
        spec_salmonella: 'Salmonella',
        spec_shelf_life: 'Shelf life',
        spec_storage: 'Storage',
        spec_accompanying_docs: 'Accompanying Documents',
        // Modals
        modal_price_title: 'Price Request',
        modal_info_title: 'Request Additional Info',
        modal_phone: 'Phone',
        modal_phone_error: 'Enter phone number',
        modal_phone_invalid: 'Invalid phone format',
        modal_quantity: 'Quantity',
        modal_quantity_error: 'Specify quantity',
        modal_quantity_placeholder: 'E.g., 100 kg, 1 ton',
        modal_comment_placeholder: 'Additional information...',
        modal_submit: 'Send Request',
        modal_success_title: 'Request Sent!',
        modal_success: 'Thank you! We will contact you shortly.',
        modal_error: 'An error occurred. Please try again later.',
    },
};

export const SEED_SETTINGS = {
    hero_title_ru: 'Экспортёр солодки\nдля B2B-клиентов',
    hero_title_en: 'Licorice Exporter\nfor B2B Clients',
    hero_subtitle_ru: 'Объёмы поставок, рынки, ключевые преимущества',
    hero_subtitle_en: 'Supply volumes, markets, key advantages',
    hero_cta_ru: 'Запросить коммерческое предложение',
    hero_cta_en: 'Request Commercial Proposal',
    email: 'bogotmaster@gmail.com',
    phone: ['+998 97 712 98 26', '+998 99 512 98 26'],
    address_ru: '220204, Боготский район, Хорезмская область, Республика Узбекистан.',
    address_en: '220204, Bogot district, Khorezm region, Republic of Uzbekistan.',
    website: 'https://bogotmaster.org',
    website_display: 'bogotmaster.org',
    whatsapp: '998995129826',
    telegram: 'e_f_r_u_z_0_0_2_6',
    gallery: Array.from({ length: 14 }, (_, i) => `/gallary photos/${i}.jpg`),
};
